### ISSUE TITLE
vcfcov and --nkmers

### ISSUE THREAD

**Issue by peterdfields** [mcveanlab/mccortex#45]
When running the standard pipeline the vcfcov step doesn't seem to include the additional NKMERS argument. This is a problem for larger graphs I've found.

**Comment by noporpoise** [comment]
On the 6th Sep  I changed the default behaviour of `vcfcov` (see commit 4f5dcd2b9f906858089305a1eac888c46fcca304) to use much less memory by doing a two-pass reading of the VCF, which only loads the required kmers. Since this calculates the exact number of required kmers this should have resolved this issue. Were you using an earlier version?

I've just updated the McCortex pipeline to pass NKMERS to the `vcfcov` command. 

Update with: `git pull && git submodule update --init --recursive && make all`

Thanks for reporting, Isaac
