### ISSUE TITLE
reads command produces an additional bogus file.

### ISSUE THREAD

**Issue by yeban** [mcveanlab/mccortex#51]
Using reads command to obtain the subset of read-pairs represented in the population graph, e.g., using the command below:

    $ mccortex31 reads -m 460G -n 6G -t 52 -2 R1.fastq.gz:R2.fastq.gz:pg pg.ctx

 produces three output files:

    pg.1.fq.gz
    pg.2.fq.gz
    pg.fq.gz

The last file is empty. And not expected, right?

**Comment by noporpoise** [comment]
The last file is for reads that could not be paired. We create it at the beginning of the run in case we hit any unpaired reads. Creating the file could fail (e.g. if we don't have permission to create the file). It's better to fail at the beginning of a task rather than hours into it. That's why we create it even though it's not needed. I hope that makes sense.
